### ISSUE TITLE
pcre-8.35.tar.gz missing in bootstrap script

### ISSUE THREAD

**Issue by Lopi** [hadojae/redonion#10]
pcre-8.35.tar.gz doesn't seem to come with the bootstrap script, I simply downloaded it from sourceforge and scp'd it over to the appropriate directory (/home/ro/redonion-master/lua_stuff)

**Comment by hadojae** [comment]
hmm, odd. pcre-8.35.tar.gz is in lua_thirdparty.tar.gz

its extracted on line 864 into the "lua_stuff" dir and begins building on line 875

**Comment by Lopi** [comment]
Hm I see, I wonder what I've done.

**Comment by Lopi** [comment]
Stems from the same issue I've been having.
