### ISSUE TITLE
More Lua Problems

### ISSUE THREAD

**Issue by Lopi** [hadojae/redonion#12]
unzip:  cannot find or open /home/ro/redonion-master/lua_stuff/lua-zlib.zip, /home/ro/redonion-master/lua_stuff/lua-zlib.zip.zip or /home/ro/redonion-master/lua_stuff/lua-zlib.zip.ZIP.

May have to manually pull this down as well, not seeing how it's pulled down by redonion.

**Comment by hadojae** [comment]
sounds like the lua archive didnt properly extract

**Comment by Lopi** [comment]
Closing this comment, I think all of the issues I'm reporting stem from the original redonion-master path issue.
