### ISSUE TITLE
pf_ring on centos6

### ISSUE THREAD

**Issue by chrisfry** [hadojae/redonion#14]
I can't get redonion to compile using the redonion_bootstrap_6.sh script, it is erroring out on (i think) the napatech drivers in pfring:

/opt/pfring/userland/lib/libpfring.a(pfring_mod_nt.o): In function `pfring_nt_close':
pfring_mod_nt.c:(.text+0x8c8): undefined reference to`NT_NetTxClose'
pfring_mod_nt.c:(.text+0x8d8): undefined reference to `NT_StatClose'
pfring_mod_nt.c:(.text+0x8e4): undefined reference to`NT_NetRxClose'
pfring_mod_nt.c:(.text+0x93a): undefined reference to `NT_NTPL'
pfring_mod_nt.c:(.text+0x959): undefined reference to`NT_ConfigClose'
/opt/pfring/userland/lib/libpfring.a(pfring_mod_nt.o): In function `pfring_nt_stats':
pfring_mod_nt.c:(.text+0x9af): undefined reference to`NT_StatRead'
/opt/pfring/userland/lib/libpfring.a(pfring_mod_nt.o): In function `pfring_nt_enable_ring':
pfring_mod_nt.c:(.text+0xb8d): undefined reference to`NT_NetRxOpen'
pfring_mod_nt.c:(.text+0xba4): undefined reference to `NT_StatOpen'
pfring_mod_nt.c:(.text+0xbe1): undefined reference to`NT_StatRead'
pfring_mod_nt.c:(.text+0xc1d): undefined reference to `NT_InfoOpen'
pfring_mod_nt.c:(.text+0xc4a): undefined reference to`NT_InfoRead'
pfring_mod_nt.c:(.text+0xc69): undefined reference to `NT_ExplainError'
pfring_mod_nt.c:(.text+0xc8e): undefined reference to`NT_InfoClose'
pfring_mod_nt.c:(.text+0xca4): undefined reference to `NT_StatClose'
pfring_mod_nt.c:(.text+0xcba): undefined reference to`NT_NetRxClose'
pfring_mod_nt.c:(.text+0xcd3): undefined reference to `NT_ExplainError'
pfring_mod_nt.c:(.text+0xd5a): undefined reference to`NT_NTPL'
pfring_mod_nt.c:(.text+0xd79): undefined reference to `NT_ConfigClose'
pfring_mod_nt.c:(.text+0xdbf): undefined reference to`NT_ConfigOpen'
pfring_mod_nt.c:(.text+0xe4a): undefined reference to `NT_NTPL'
pfring_mod_nt.c:(.text+0xe8b): undefined reference to`NT_ExplainError'
pfring_mod_nt.c:(.text+0xed3): undefined reference to `NT_ExplainError'
pfring_mod_nt.c:(.text+0xf13): undefined reference to`NT_InfoClose'
pfring_mod_nt.c:(.text+0xf3b): undefined reference to `NT_NetTxOpen'
pfring_mod_nt.c:(.text+0xf5a): undefined reference to`NT_ExplainError'
/opt/pfring/userland/lib/libpfring.a(pfring_mod_nt.o): In function `pfring_nt_send':
pfring_mod_nt.c:(.text+0x106d): undefined reference to`NT_NetTxGet'
pfring_mod_nt.c:(.text+0x10a5): undefined reference to `NT_NetTxRelease'
pfring_mod_nt.c:(.text+0x1140): undefined reference to`NT_ExplainError'
pfring_mod_nt.c:(.text+0x1179): undefined reference to `NT_ExplainError'
/opt/pfring/userland/lib/libpfring.a(pfring_mod_nt.o): In function`pfring_nt_recv_chunk':
pfring_mod_nt.c:(.text+0x11f3): undefined reference to `NT_NetRxGet'
pfring_mod_nt.c:(.text+0x1231): undefined reference to`NT_NetRxRelease'
pfring_mod_nt.c:(.text+0x1246): undefined reference to `NT_NetRxRelease'
/opt/pfring/userland/lib/libpfring.a(pfring_mod_nt.o): In function`pfring_nt_recv':
pfring_mod_nt.c:(.text+0x1761): undefined reference to `NT_NetRxGetNextPacket'
/opt/pfring/userland/lib/libpfring.a(pfring_mod_nt.o): In function`__pfring_nt_get_new_stream_id':
pfring_mod_nt.c:(.text+0x1f69): undefined reference to `NT_InfoOpen'
pfring_mod_nt.c:(.text+0x1f8b): undefined reference to`NT_InfoRead'
pfring_mod_nt.c:(.text+0x1fe5): undefined reference to `NT_InfoClose'
pfring_mod_nt.c:(.text+0x1ff6): undefined reference to`NT_InfoClose'
pfring_mod_nt.c:(.text+0x202d): undefined reference to `NT_ExplainError'
pfring_mod_nt.c:(.text+0x2063): undefined reference to`NT_ExplainError'
pfring_mod_nt.c:(.text+0x2088): undefined reference to `NT_InfoClose'
/opt/pfring/userland/lib/libpfring.a(pfring_mod_nt.o): In function`__pfring_nt_check_ports':
pfring_mod_nt.c:(.text+0x20d2): undefined reference to `NT_InfoOpen'
pfring_mod_nt.c:(.text+0x2138): undefined reference to`NT_InfoRead'
pfring_mod_nt.c:(.text+0x2165): undefined reference to `NT_InfoClose'
pfring_mod_nt.c:(.text+0x21a8): undefined reference to`NT_ExplainError'
pfring_mod_nt.c:(.text+0x21cd): undefined reference to `NT_InfoClose'
pfring_mod_nt.c:(.text+0x21e6): undefined reference to`NT_InfoClose'
pfring_mod_nt.c:(.text+0x2204): undefined reference to `NT_ExplainError'
/opt/pfring/userland/lib/libpfring.a(pfring_mod_nt.o): In function`pfring_nt_open':
pfring_mod_nt.c:(.text+0x23f0): undefined reference to `NT_InfoOpen'
pfring_mod_nt.c:(.text+0x2415): undefined reference to`NT_InfoRead'
pfring_mod_nt.c:(.text+0x2442): undefined reference to `NT_InfoRead'
pfring_mod_nt.c:(.text+0x2472): undefined reference to`NT_InfoRead'
pfring_mod_nt.c:(.text+0x2a02): undefined reference to `NT_InfoClose'
pfring_mod_nt.c:(.text+0x2ded): undefined reference to`NT_Init'
pfring_mod_nt.c:(.text+0x2e0c): undefined reference to `NT_ExplainError'
pfring_mod_nt.c:(.text+0x2fd3): undefined reference to`NT_ExplainError'
pfring_mod_nt.c:(.text+0x3019): undefined reference to `NT_ExplainError'
pfring_mod_nt.c:(.text+0x3050): undefined reference to`NT_ExplainError'
pfring_mod_nt.c:(.text+0x3075): undefined reference to `NT_InfoClose'
collect2: ld returned 1 exit status
make[1]: *** [all] Error 1
make[1]: Leaving directory`/home/ro/redonion/moloch/capture'
make: **\* [all-recursive] Error 1
MOLOCH: make failed
[*] Failure...exiting...

**Comment by hadojae** [comment]
interesting, but bro and suri built ok? i can do a build in a bit and see if i can replicate. What kernel are you on?

**Comment by chrisfry** [comment]
# uname -r

2.6.32-573.12.1.el6.x86_64

bro built ok

[*] BRO install has completed.

suricata errored on some luarocks zzip IIRC

I have the same problem napatech references even when i just do the
-moloch flag for the bootstrap script.

thx for having a look

**Comment by phreakinggeek** [comment]
Did you read https://github.com/hadojae/redonion/wiki/Red-Onion-Installation-Guide and https://github.com/hadojae/redonion/wiki/RHEL-Packages - I've run into the luarocks issues when I forgot to install the deps outlined there.

Hope that helps!

**Comment by chrisfry** [comment]
yeah, was able to get through the luarocks issue. i've tried a fresh install and running only the moloch installer from the bootstrap script and get the same problem. I really only want the moloch piece, don't care about bro/suricata so much.

**Comment by hadojae** [comment]
Until i can sort it out, if you only want moloch you should use their installer script at http://github.com/aol/moloch. Pull it down and run ./easybutton-singlehost.sh and follow their prompts. Would be interested to know if you have the same pfring issue there.

**Comment by chrisfry** [comment]
k will give it a shot and let you know

**Comment by Lickitysplitted** [comment]
I've also come across these errors. Has there been any further development of this?

**Comment by hadojae** [comment]
Odd things can happen when/if the install script gets run a few times over itself. The script tries to clean up after itself, but there could certainly be things missing. I will add a few things to the troubleshooting section of the wiki. Sometimes kernel updates can cause the pfring install/dkms upgrade to fail. I am going to make an install video and checklist document of install to help this process as it's where i've heard people having the most issues.

**Comment by hadojae** [comment]
I am going to close this issue as I was not able to repro the issue initially and it has been a while. @Lickitysplitted please let me know after fresh install the exact error you are seeing and we'll get it working. @chrisfry assuming you just wanted moloch, hopefully the install direct from their git worked.
