### ISSUE TITLE
Trouble installing moloch on centos 7.3

### ISSUE THREAD

**Issue by ghost** [hadojae/redonion#15]
Hi!
thanks for providing the build script!

I fail installing moloch on centos 7.3 because it tries to pull yara from http://yara-project.googlecode.com. Since yara moved to github it fails.

Greetings
Daniel

**Comment by ghost** [comment]
seems to be a moloch issue. I'll open an issue there...

**Comment by hadojae** [comment]
this is fixed in current moloch, i need to update my fork, thanks for the heads up!

**Comment by hadojae** [comment]
updated moloch fork with the proper url, need to update that whole fork however

**Comment by ghost** [comment]
The URL in moloch repo is newer but also dead. I opened an issue there.
Maybe you can just use the rpms which moloch provides. I successfully installed moloch with the rpm.
```
$ yum install http://files.molo.ch/builds/centos-7/moloch-0.17.0-1.x86_64.rpm
[...]
Installed:
  moloch.x86_64 0:0.17.0-1
Complete!

```

**Comment by hadojae** [comment]
hm, https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/yara-project/yara-1.7.tar.gz works for me. If not using pfring, the package is certainly a solution. if using pfring, it gets more complicated as you can end up with one tool not using pfring or multiple installed versions of pfring on one system which i have seen get confusing very quickly when troubleshooting issues.

**Comment by ghost** [comment]
yeah, just tested it again and it works. yesterday it did not. wired.
