### ISSUE TITLE
Error: must run broctl only on manager node

### ISSUE THREAD

**Issue by ghost** [hadojae/redonion#2]
[worker-1]
type=worker
host=172.16.231.217
interface=eth1
lb_method=pf_ring
lb_procs=4
[_] cleanup...
[_] Success!
Error: must run broctl only on manager node
[*] Failure...exiting...

---

Have you ran into this?

**Comment by hadojae** [comment]
Yep, this occurs when the bro manager is on a different IP than the host running broctl. Usually when installing this the manager node in the node.cfg should be defined as the same IP as the worker.
