### ISSUE TITLE
Also issues with lua

### ISSUE THREAD

**Issue by ghost** [hadojae/redonion#3]
[_] Decompressing Lua Thirdparty Modules
tar (child): /home/gps/redonion-master/lua_thirdparty.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[_] Success!
tar (child): pcre-8.35.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[*] Failure...exiting...

**Comment by hadojae** [comment]
Have seen this error when lua_thirdparty.gz isn't present in the working_dir. If you git clone redonion, it should be in the proper place.

**Comment by ghost** [comment]
Yeah I did git clone redonion
