### ISSUE TITLE
Still issues with lua

### ISSUE THREAD

**Issue by ghost** [hadojae/redonion#4]
Complete!
[_] Decompressing Lua Thirdparty Modules
tar (child): /home/ro/redonion-master/lua_thirdparty.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[_] Success!
tar (child): pcre-8.35.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[*] Failure...exiting...

I'm running the script from the git clone location

**Comment by hadojae** [comment]
Does /home/ro/redonion-master/lua_thirdparty.tar.gz exist?
