### ISSUE TITLE
Fix is_logstash_running variable in ro_persist.sh to work as intended.

### ISSUE THREAD

**Issue by phreakinggeek** [hadojae/redonion#7]
https://github.com/hadojae/redonion/blob/master/config/ro_persist.sh#L79-L81

s/is_viewer_running/is_logstash_running for these lines to reflect on the var being called upon on in line 108 (below).

https://github.com/hadojae/redonion/blob/master/config/ro_persist.sh#L108
With the current configuration 'is_logstash_running' will always be 0 causing logstash to either restart or go cuckoo bananas and spawn a bunch of erroneous instances.

**Comment by hadojae** [comment]
fixed, thanks
