### ISSUE TITLE
Create /home/ro/redonion-master automagically in the bootstrap script

### ISSUE THREAD

**Issue by Lopi** [hadojae/redonion#9]
/home/ro/redonion-master is not automagically created in the bootstrap 7 script

This is easy to fix manually:

su ro
mkdir ~/redonion-master
exit

Run bootstrap script again.

**Comment by hadojae** [comment]
I didn't want to force anyone to install to a singular location, you can change the wrk_dir variable at the top of the script to be wherever you want to extract from. I will change the default directory to match the default git clone. Thanks!

**Comment by Lopi** [comment]
Thanks man!
